title: Thầy Khải - Hóa học
description: Luyện thi THPT Quốc gia môn Hóa học
author: Thầy Khải - Hóa học
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/codeasashu
about: Luyện thi THPT Quốc gia môn Hóa học

baseurl: "https://dodinhkhai.github.io"
url: "https://dodinhkhai.github.io"

allowsearch: true

disqus_shortname: Khải
google_analytics: %UA-72862926-1%

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
